# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: info_manager.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'info_manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12info_manager.proto\x12\x0cinfo_manager\"H\n\x0bInfoRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x66\x61mily\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x03\x12\x0e\n\x06is_new\x18\x04 \x01(\x08\"\x1b\n\rIsInfoCorrect\x12\n\n\x02ok\x18\x01 \x01(\x08\x32S\n\x0bInfoManager\x12\x44\n\x08SendInfo\x12\x19.info_manager.InfoRequest\x1a\x1b.info_manager.IsInfoCorrect\"\x00\x42\x39\n\x1dio.grpc.examples.info_managerB\x10InfoManagerProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'info_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035io.grpc.examples.info_managerB\020InfoManagerProtoP\001\242\002\003HLW'
  _globals['_INFOREQUEST']._serialized_start=36
  _globals['_INFOREQUEST']._serialized_end=108
  _globals['_ISINFOCORRECT']._serialized_start=110
  _globals['_ISINFOCORRECT']._serialized_end=137
  _globals['_INFOMANAGER']._serialized_start=139
  _globals['_INFOMANAGER']._serialized_end=222
# @@protoc_insertion_point(module_scope)
