# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import info_manager_pb2 as info__manager__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in info_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InfoManagerStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendInfo = channel.unary_unary(
                '/info_manager.InfoManager/SendInfo',
                request_serializer=info__manager__pb2.InfoRequest.SerializeToString,
                response_deserializer=info__manager__pb2.IsInfoCorrect.FromString,
                _registered_method=True)


class InfoManagerServicer(object):
    """The greeting service definition.
    """

    def SendInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InfoManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SendInfo,
                    request_deserializer=info__manager__pb2.InfoRequest.FromString,
                    response_serializer=info__manager__pb2.IsInfoCorrect.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'info_manager.InfoManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('info_manager.InfoManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InfoManager(object):
    """The greeting service definition.
    """

    @staticmethod
    def SendInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/info_manager.InfoManager/SendInfo',
            info__manager__pb2.InfoRequest.SerializeToString,
            info__manager__pb2.IsInfoCorrect.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
